version: "3.8"
services:
  wargame-nginx:
    depends_on:
      - wargame-frontend
      - wargame-backend
    build:
      dockerfile: Dockerfile
      context: ../Nginx
    container_name: wargame-nginx
    ports:
      - 80:80
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wargame-frontend:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 4000-4002:3000
    deploy:
      mode: replicated
      replicas: 3

  wargame-backend:
    build:
      dockerfile: Dockerfile
      context: ../backend
    volumes:
      - /app/node_modules
      - ../backend:/app
    ports:
      - 4010-4011:3001
    deploy:
      mode: replicated
      replicas: 2
