version: "3.8"
services:
  wargame-nginx:
    depends_on:
      - wargame-backend
    build:
      dockerfile: Dockerfile
      context: ../Nginx/
    container_name: wargame-nginx
    ports:
      - 31337:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  wargame-backend:
    build:
      dockerfile: Dockerfile
      context: ../backend
    volumes:
      - /app/node_modules
      - ../backend:/app
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    restart: unless-stopped
