version: "3.8"
services:
  wargame-nginx:
    depends_on:
      - wargame-frontend-1
      - wargame-frontend-2
      - wargame-frontend-3
      - wargame-backend-1
      - wargame-backend-2
    build:
      dockerfile: Dockerfile
      context: ../Nginx
    container_name: wargame-nginx
    ports:
      - 80:80
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wargame-frontend-1:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-1
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 4000:3000

  wargame-frontend-2:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-2
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 4001:3000

  wargame-frontend-3:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-3
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 4002:3000

  wargame-backend-1:
    build:
      dockerfile: Dockerfile
      context: ../backend
    container_name: wargame-backend-1
    volumes:
      - /app/node_modules
      - ../backend:/app
    ports:
      - 4010:3001

  wargame-backend-2:
    build:
      dockerfile: Dockerfile
      context: ../backend
    container_name: wargame-backend-2
    volumes:
      - /app/node_modules
      - ../backend:/app
    ports:
      - 4011:3001
