version: "3.8"
services:
  wargame-nginx:
    depends_on:
      - wargame-frontend-1
      - wargame-frontend-2
      - wargame-frontend-3
      - wargame-backend
    build:
      dockerfile: Dockerfile
      context: ../Nginx
    container_name: wargame-nginx
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wargame-frontend-1:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-1
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 3000:3000

  wargame-frontend-2:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-2
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 3002:3000

  wargame-frontend-3:
    build:
      dockerfile: Dockerfile
      context: ../frontend
    container_name: wargame-frontend-3
    volumes:
      - /app/node_modules
      - ../frontend:/app
    ports:
      - 3003:3000

  wargame-backend:
    build:
      dockerfile: Dockerfile
      context: ../backend
    container_name: wargame-backend
    volumes:
      - /app/node_modules
      - ../backend:/app
    ports:
      - 3001:3001
